# Site settings
title: HA Mate landing page
email: someemail@email.com
description: Demo site for the GitBook-inspired documentation theme for Jekyll
url: "https://immrmkw.github.io"
baseurl: "/HA_Mate"
timezone: Europe/Brussels

# Build settings
remote_theme: adamrehn/jekyll-theme-gitbook
markdown: kramdown
kramdown:
  input: GFM
exclude: [".gitignore", "LICENSE", "README.md"]
sass:
  style: compressed

# Only needed for local development, will be enabled automatically by GitHub Pages
plugins: 
  - jekyll-remote-theme


# host: 127.0.0.1
# # the preview server used. Leave as is.

# port: 4000
# # the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.

# highlighter: rouge
# # library used for syntax highlighting


# Theme settings
theme-settings:
  
  # Copyright settings
  copyright:
    author: "[IMMRMKW](https://github.com/IMMRMKW)"
    license: "Licensed under the MIT License, see the file [LICENSE](https://github.com/adamrehn/jekyll-theme-gitbook-demo/blob/master/LICENSE) for details."
    year: 2024
  
  # The collection that contains our chapters
  collection: chapters
  
  # Enable generation of links for chapter index pages
  indices: false

# Configure the permalinks for each chapter
collections_dir: _collections
collections:
  chapters:
    output: true
    permalink: /:path

# Use front matter defaults to supply the metadata for each chapter
defaults:
  -
    scope:
      path: ""
      type: "chapters"
    values:
      layout: "default"
  -
    scope:
      path: "_collections/_chapters/1-Installing-ESPHome"
    values:
      chapter: "Installing ESPHome"
      chapnum: 1
  -
    scope:
      path: "_collections/_chapters/2-Ventimate"
    values:
      chapter: "Ventimate"
      chapnum: 2
  -
    scope:
      path: "_collections/_chapters/3-Plantmate"
    values:
      chapter: "Plantmate"
      chapnum: 3
