name: build-gem
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      # Clone the source code on the runner
      - uses: actions/checkout@v3
      
      # Perform setup for Ruby 2.7
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.4'
          rubygems: latest
          bundler-cache: true
      
      # Publish the gem to RubyGems when a new release is tagged
      - if: startsWith(github.ref, 'refs/tags')
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem push *.gem
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.6.0'

      - name: Install dependencies
        run: npm install -g sharp

      - name: Check installed packages
        run: npm list -g --depth=0

      - name: Generate thumbnails
        run: |
          mkdir -p assets/images/Plant-database/thumbnails
          npx sharp assets/images/Plant-database/*.jpg \
            --resize 100x100 \
            --output assets/images/Plant-database/thumbnails/

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add assets/images/Plant-database/thumbnails
          git commit -m 'Generate thumbnails'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
